[package]
name = "factorial-logic"
version = "0.1.0"
edition = "2024"

[dependencies]
factorial-core = { path = "../factorial-core" }
bitcode = { workspace = true }
fixed = { workspace = true }
serde = { workspace = true }
slotmap = { workspace = true }
