[package]
name = "factorial-demo-bevy"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
factorial-demo-core = { path = "../factorial-demo-core" }
factorial-core = { path = "../factorial-core" }
bevy = "0.15"
