[package]
name = "factorial-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
factorial-core = { path = "../factorial-core" }
fixed = { workspace = true }

[dev-dependencies]
slotmap = { workspace = true }
